### ISSUE TITLE
cannot run bugscanner 

### ISSUE THREAD

**Issue by zetsu22** [aztecrabbit/bugscanner#11]
i installed bugscanner on termux the installation goes well but when i run it by this command $ bugscanner an error show here the error i put it
~ $ bugscanner
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 33, in <module>
    sys.exit(load_entry_point('bugscanner==0.1.5', 'console_scripts', 'bugscanner')())
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/bugscanner/__init__.py", line 1, in <module>
    from .bug_scanner import BugScanner
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/bugscanner/bug_scanner.py", line 1, in <module>
    import multithreading
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/multithreading/__init__.py", line 1, in <module>
    from multithreading.logger import Logger
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/~ $ bugscanner
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 33, in <module>
    sys.exit(load_entry_point('bugscanner==0.1.5', 'console_scripts', 'bugscanner')())
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/bugscanner/__init__.py", line 1, in <module>
    from .bug_scanner import BugScanner
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/bugscanner/bug_scanner.py", line 1, in <module>
    import multithreading
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/multithreading/__init__.py", line 1, in <module>
    from multithreading.logger import Logger
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/multithreading/logger.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'/logger.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by aztecrabbit** [comment]
Duplicate issue.

#9
