### ISSUE TITLE
issue when running bugscanner

### ISSUE THREAD

**Issue by nziom** [aztecrabbit/bugscanner#9]
~ $ bugscanner
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 33, in <module>
    sys.exit(load_entry_point('bugscanner==0.1.8', 'console_scripts', 'bugscanner')())
  File "/data/data/com.termux/files/usr/bin/bugscanner", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bugscanner-0.1.8-py3.9.egg/bugscanner/__init__.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/bugscanner-0.1.8-py3.9.egg/bugscanner/bug_scanner.py", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/multithreading/__init__.py", line 1, in <module>
    from multithreading.logger import Logger
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/multithreading/logger.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

**Comment by aztecrabbit** [comment]
install loguru module first,

```
$ pip install loguru
```

and install module again if something like this happend.

**Comment by nziom** [comment]
Another error occurred 
~/bugscanner/bugscanner $ python direct_scanner.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/bugscanner/bugscanner/direct_scanner.py", line 1, in <module>
    from .bug_scanner import BugScanner
ImportError: attempted relative import with no known parent package

**Comment by aztecrabbit** [comment]
Not like that. First, you need to install this script, don't direct run like that

```
pip install bugscanner
```

and then use command like in this tutorial [here](https://github.com/aztecrabbit/bugscanner#usage)
